remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Julio Cesar Torres
submodulo: introduccion a la programaion
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/imagen-adb62.appspot.com/o/IMG_20230127_053129_038.jpg?alt=media&token=dec8db22-32d1-44da-906d-d8eeb3a9fff1


